
GET http://localhost:3000/users/661599e796015a91dbc0e96e
###
POST http://localhost:3000/file
Content-Type: application/json

{
    "fileName": 'example.txt',
      "size": 1024,
      "pathToFile": "/path/to/example.txt",
      "fileType": "text/plain",
      "fileOwner": "john_doe",
      "sha": "123abc",
}

###
DELETE http://localhost:3000/users/661599e796015a91dbc0e96e

###
PATCH http://localhost:3000/users/661424e4ec3ebebcb8b2374f
Content-Type: application/json

{
    "name": "user 2"
}